name: Release

on:
  release:
    types: [published]

jobs:

  release_zip:
    name: Prepare release
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Download Lokalise CLI
        run: |
          curl -sSL \
            "https://github.com/lokalise/lokalise-cli-2-go/releases/download/v2.6.2/lokalise2_linux_x86_64.tar.gz" \
            -o ./lokalise.gz
          tar -xvzf ./lokalise.gz

      - name: Downloading translations
        run: |
          ./lokalise \
              --token "${{ secrets.LOKALISE_TOKEN }}" \
              export "581188395e9778a6060128.17699416" \
              --type json \
              --unzip_to  /tmp/lokalise \
              --filter last_reviewed_only \
              --export_empty skip \
              --export_sort a_z

      - name: Move new translations
        run: |
          mkdir -p /home/runner/work/homeassistant-mikrotik_router/homeassistant-mikrotik_router/custom_components/mikrotik_router/translations/
          cp /tmp/lokalise/locale/* /home/runner/work/homeassistant-mikrotik_router/homeassistant-mikrotik_router/custom_components/mikrotik_router/translations/

      - name: Zip mikrotik_router dir
        run: |
          cd /home/runner/work/homeassistant-mikrotik_router/homeassistant-mikrotik_router/custom_components/mikrotik_router
          zip mikrotik_router.zip -r ./
      - name: Upload zip to release
        uses: svenstaro/upload-release-action@v1-release

        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: /home/runner/work/homeassistant-mikrotik_router/homeassistant-mikrotik_router/custom_components/mikrotik_router/mikrotik_router.zip
          asset_name: mikrotik_router.zip
          tag: ${{ github.ref }}
          overwrite: true

  releasenotes:
    name: Prepare releasenotes
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Install requirements
        run: |
          python3 -m pip install setuptools wheel PyGithub

      - name: Update release notes
        run: |
          python3 /home/runner/work/homeassistant-mikrotik_router/homeassistant-mikrotik_router/.github/generate_releasenotes.py --token ${{ secrets.GITHUB_TOKEN }} --release yes --tag ${{ github.ref }}
